Repository typewriter221/Cerebral-Microbleed-Classification, pull requests merged in 2023-10, with the labels that each got.

#5 Added descriptive Readme file
  README.md
Labels: good first issue, hacktoberfest-accepted

#6 Added cerbral_v3 by training on a new model
  Cerbral_v3_0.ipynb
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#8 Added description to Readme File
  README.md
Labels: hacktoberfest, hacktoberfest-accepted
